name: cinephoria_mobile
description: "Application mobile pour Cinéphoria."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.3
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.2.3

dev_dependencies:
  mockito: ^5.3.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  assets:
    - assets/images/logo.png
  uses-material-design: true
